Repository itcen-project-2team/drawcen-web, pull requests merged in 2025-06, with the labels that each got.

#24 Feature/#23 auth flow
  src/pages/landingpage/LandingPage.jsx
  src/pages/main/Main.jsx
  src/services/userService.js
  src/stores/userStore.js
Labels: enhancement, auth

#25 [feat] #23 - 인증 플로우 2
  src/components/PageWrapper/PageWrapper.jsx
  src/index.js
  src/pages/gameroom/GameRoom.jsx
  src/pages/landingpage/LandingPage.jsx
  src/pages/main/Main.css
  src/pages/main/Main.jsx
  src/services/userService.js
  src/stores/userStore.js
  src/styles/global.css
  src/styles/pageTransition.css
  src/utils/api.js
  src/utils/handleApiError.js
Labels: enhancement, auth

#28 [feat] 게임 웹소캣 연동
  .gitignore
  package-lock.json
  package.json
  src/components/modal/RankingModal.jsx
  src/components/modal/RankingModal.module.css
  src/components/room/WaitingRoomModal.css
  src/components/room/WaitingRoomModal.jsx
  src/pages/gameroom/Canvas.jsx
  src/pages/gameroom/Canvas.module.css
  src/pages/gameroom/ChatBox.jsx
  src/pages/gameroom/ChatBox.module.css
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/GameRoom.module.css
  src/pages/gameroom/PlayerList.jsx
  src/pages/gameroom/PlayerList.module.css
  src/pages/main/Main.css
  src/pages/main/Main.jsx
  src/routes/AppRouter.jsx
  src/services/roomService.js
  src/services/userService.js
  src/utils/api.js
  src/utils/websocket.js
Labels: websocket

#31 [feat] #26 - 랜덤 닉네임 생성 및 닉네임 수정 기능
  src/pages/main/Main.css
  src/pages/main/Main.jsx
  src/services/userService.js
Labels: enhancement, auth

#33 [feat] #32 - 웹소켓 연결 수립 전에 accesstoken 만료 여부 체크 및 재발급
  src/assets/backgroud-music.mp3
  src/utils/websocket.js
Labels: enhancement, auth

#37 [feat] #29 - 게임 룰 설명 추가 / 그림 순서 변경 / 타이머와 룰 설명 단추 랜더링 UX 개선
  src/assets/playguide-01.png
  src/assets/playguide-02.png
  src/assets/playguide-03.png
  src/pages/landingpage/LandingPage.css
  src/pages/landingpage/LandingPage.jsx
Labels: ui

#44 [feat] #43 - csrf 토큰 담도록
  src/utils/api.js
Labels: auth

#45 [refactor] #36 - 버튼 uiux 수정
  src/assets/setting.png
  src/components/modal/SettingsDropdown.jsx
  src/components/modal/SettingsDropdown.module.css
  src/components/musicControl/MusicControl.jsx
  src/pages/gameroom/Canvas.jsx
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/GameRoom.module.css
  src/pages/main/Main.css
  src/pages/main/Main.jsx
Labels: ui
